name: example
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  args: ^2.7.0

dev_dependencies:
  pub2yocto:
    path: ..
  intl:
    git:
      path: pkgs/intl/
      url: https://github.com/dart-lang/i18n.git
      ref: main
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
