name: pub2yocto
description: A Dart package to convert pubspec.lock file to Yocto recipes.
version: 0.4.3
repository: https://github.com/SeungkyunKim/pub2yocto

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  yaml: ^3.1.3
  http: ^1.3.0
  args: ^2.7.0
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
